In [ ]:
print(type("hello world"))


<class 'str'>


In [ ]:
print("hello world")

hello world


In [ ]:
a=2
b=3
print(a+b)
print(type(a+b))

5
<class 'int'>


TypeError: type() takes 1 or 3 arguments

In [ ]:
a=int (input())
b=int (input())
print(a+b)
print (type(a+b))

2
3
5
<class 'int'>


In [ ]:
a=int (input())
b= int(input())
c=a+b
print(c)
print (type(c))

2
3
5
<class 'int'>


In [ ]:
for i in range(1,11):
  print(i)


1
2
3
4
5
6
7
8
9
10


In [ ]:
i = 1
while i <= 50:
    if i % 5 == 0:
        print(i)
    i += 1


5
10
15
20
25
30
35
40
45
50


In [ ]:
i = 1
while i<=50:
  if i %5==0:
    print(i)
  i += 1

5
10
15
20
25
30
35
40
45
50


In [ ]:
for i in range(0, 100):
    count = 0

    for j in range(1, i):
        if i % j == 0:
            print(j)

1
1
1
2
1
1
2
3
1
1
2
4
1
3
1
2
5
1
1
2
3
4
6
1
1
2
7
1
3
5
1
2
4
8
1
1
2
3
6
9
1
1
2
4
5
10
1
3
7
1
2
11
1
1
2
3
4
6
8
12
1
5
1
2
13
1
3
9
1
2
4
7
14
1
1
2
3
5
6
10
15
1
1
2
4
8
16
1
3
11
1
2
17
1
5
7
1
2
3
4
6
9
12
18
1
1
2
19
1
3
13
1
2
4
5
8
10
20
1
1
2
3
6
7
14
21
1
1
2
4
11
22
1
3
5
9
15
1
2
23
1
1
2
3
4
6
8
12
16
24
1
7
1
2
5
10
25
1
3
17
1
2
4
13
26
1
1
2
3
6
9
18
27
1
5
11
1
2
4
7
8
14
28
1
3
19
1
2
29
1
1
2
3
4
5
6
10
12
15
20
30
1
1
2
31
1
3
7
9
21
1
2
4
8
16
32
1
5
13
1
2
3
6
11
22
33
1
1
2
4
17
34
1
3
23
1
2
5
7
10
14
35
1
1
2
3
4
6
8
9
12
18
24
36
1
1
2
37
1
3
5
15
25
1
2
4
19
38
1
7
11
1
2
3
6
13
26
39
1
1
2
4
5
8
10
16
20
40
1
3
9
27
1
2
41
1
1
2
3
4
6
7
12
14
21
28
42
1
5
17
1
2
43
1
3
29
1
2
4
8
11
22
44
1
1
2
3
5
6
9
10
15
18
30
45
1
7
13
1
2
4
23
46
1
3
31
1
2
47
1
5
19
1
2
3
4
6
8
12
16
24
32
48
1
1
2
7
14
49
1
3
9
11
33


In [ ]:
import math
for num in range (2,101):
  is_prime = True

  for i in range (2,int(math.sqrt(num))+1):
    if num %1 == 0 :
      is_prime = False
      break

  if  is_prime:
    print(num, end="")

23

In [ ]:
def greet(name):
    return f"Hello, {name}!"

print(greet("Rahul"))

Hello, Rahul!


In [ ]:
def sum(a,b,c):
 return(a+b+c)

 a=int(input())
 b =int(input())
 c=int(input())
 sum(a+b+c)

In [ ]:
animal = [ "cat" , "dog" , "cow" , "whale" , "pig" ]
print(animal)
for i in animal:
  print(i.upper())


['cat', 'dog', 'cow', 'whale', 'pig']
CAT
DOG
COW
WHALE
PIG


In [ ]:
animal = [ "cat" , "dog" , "cow" , "whale" , "pig" ]


{0: 'cat', 1: 'dog', 2: 'cow', 3: 'whale', 4: 'pig'}


In [ ]:
def divisible():
  for i in range (x,y):
    if i%2==0 and i%3==0 and i%5==0:
      print(i)
def div():
 for i in range (x,y):
  if i%6==0 and i%7==0:
    print(i)

x=int(input())
y=int(input())
print ("divisible by 2")
divisible()
print ("divisible by 3")
divisible()
print ("divisible by 5")
divisible()
print ("divisible by 6,7")
div()

1
100
divisible by 2
30
60
90
divisible by 3
30
60
90
divisible by 5
30
60
90
divisible by 6,7
42
84


In [ ]:
def divisible():
  for i in range(x,y+1):
    if i%2==0 and i%3==0 and i%5==0:
      print(i)
def div():
   for i in range(x,y+1):
    if i%6==0 and i%7==0:
      print(i)

x= int(input("enter value of x: "))
y= int(input("enter value of y: "))

print ("divisivle by 2,3,5")
divisible()
print ("divisivle by 6,7")
div()


enter value of x: 1
enter value of y: 100
divisivle by 2,3,5
30
60
90
divisivle by 6,7
42
84


In [ ]:
h ="maheedhar"
print(h[:5:-1])

rah


In [ ]:
def messages():
    count = 0

    def inner():
        nonlocal count
        count += 1

        if count == 1:
            return "hello"
        elif count == 2:
            return "hi"
        elif count == 3:
            return "how are you"
        else:
            return "No more messages"

    return inner


# Creating the function
f = messages()

print(f())  # hello
print(f())  # hi
print(f())  # how are you
print(f())  # No more messages

hello
hi
how are you
No more messages


In [ ]:
a=int(input())
b=int(input())
def check(a, b):
    total = a + b

    if total == 5:
        result = [1, 2, 3, 4, 5]
        print(result)

    elif total > 5:
        result = {1, 2, 3, 4, 5}
        print(result)

    else:
        list1 = [a * i for i in range(1, 6)]
        list2 = [b * i for i in range(1, 6)]
        result = [list1, list2]
        print(result)

check(a,b)





2
1
[[2, 4, 6, 8, 10], [1, 2, 3, 4, 5]]


date 11/05/26 data science

In [1]:
marks = 72

if marks >= 90:
    grade = "A+"
elif marks >= 80:
    grade = "A"
elif marks >= 70:
    grade = "B"
elif marks >= 60:
    grade = "C"
else:
    grade = "Fail"

print(grade)

B


In [ ]:
class Car:
    def __init__(self,brand,milage,color):
        self.brand  = brand
        self.milage   = milage
        self.color = color
    def get_info(self):
      return f"i have a car of brand {self.brand} and milage is {self.milage} and color is {self.color}"
      car

In [2]:
class Car:

    def __init__(self, brand, color, milage):
        self.brand = brand
        self.color = color
        self.milage = milage

    def __repr__(self):
        return f"Car(brand='{self.brand}', color='{self.color}', milage={self.milage})"


C1 = Car("Toyota", "Red", 25)
C2 = Car("Honda", "Blue", 30)
C3 = Car("Ford", "Green", 20)
C4 = Car("Tesla", "Black", 35)

print(C1)
print(C2)
print(C3)
print(C4)

Car(brand='Toyota', color='Red', milage=25)
Car(brand='Honda', color='Blue', milage=30)
Car(brand='Ford', color='Green', milage=20)
Car(brand='Tesla', color='Black', milage=35)


In [3]:
from abc import ABC, abstractmethod
# Abstract Class
class Car(ABC):
    def __init__(self, color, mileage):
        # Encapsulation
        self.__color = color
        self.__mileage = mileage
    # Getter methods
    def get_color(self):
        return self.__color
    def get_mileage(self):
        return self.__mileage
    # Abstract method (Polymorphism)
    @abstractmethod
    def get_info(self):
        pass
# Inheritance
class Tesla(Car):
    # Polymorphism - own implementation
    def get_info(self):
        return f"Tesla Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
class BMW(Car):
    # Polymorphism - own implementation
    def get_info(self):
        return f"BMW Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
class Audi(Car):
    # Polymorphism - own implementation
    def get_info(self):
        return f"Audi Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
# Objects
car1 = Tesla("Red", 500)
car2 = BMW("Black", 400)
car3 = Audi("White", 450)

# Polymorphism - same method name, different implementations
cars = [car1, car2, car3]
for car in cars:
    print(car.get_info())

Tesla Car of Color: Red, Mileage: 500 km
BMW Car of Color: Black, Mileage: 400 km
Audi Car of Color: White, Mileage: 450 km


In [6]:
mylist = ()
 1Integer,
Float,
String,
Boolean,
List,
Tuple,
Dictionary,
Set, NoneType,
)

print(my_list)

IndentationError: unexpected indent (3443905038.py, line 2)

create a list of one value print that and create a new list of five values  print that one now combine these two and print them

In [17]:
l=[20 ,25,35,45,65]
print(l)
l2 =[30,40,50,60,70]
print(l2)
l3=[l+l2]
print(l3)
print (l3[1][3])

[20, 25, 35, 45, 65]
[30, 40, 50, 60, 70]
[[20, 25, 35, 45, 65, 30, 40, 50, 60, 70]]


IndexError: list index out of range

leanr about matrix used in pythin like
list1.list2 means it is two lists side by side contecation means combining start with 0 index and ends at n index
list represenation [0]
[1,2,3]
[[1,2][3,4]
[[[1,2],[3,4],[[5,6],[7,8]]
import numpy as np and convert the list into array using fuction np.array
and we have string manipulation like slicing etc same all those methods can be applied to all og these also take list of 1 d list and then take 2d values and perform all those methods on 2d take same values in the both

In [25]:
s = [[1,2,3],[3,4,5],[5,6,7]]
s1=np.array(s)
print (s1[1])

[3 4 5]


In [22]:
import numpy as np

v1= np.array([1,2,3,4,5,6,7,8,9,10])


print(v1+5)
print(v1*2)
print(v1[1:5])
print(v1[::-1])
print(v1[0:5:-1])

[ 6  7  8  9 10 11 12 13 14 15]
[ 2  4  6  8 10 12 14 16 18 20]
[2 3 4 5]
[10  9  8  7  6  5  4  3  2  1]
[]


In [23]:
s = [[1,2,3],[3,4,5],[5,6,7]]

s1= np.array(s)

print(s1[1])
print(s1[2])
print(s1[-1])
print(s1[1][1])
print(s1[1][-1])
print(s1[-1][-2])
print(s1[1][0])


s1[0][0]=12
s2=(s1+s1)
print(s2)

[3 4 5]
[5 6 7]
[5 6 7]
4
5
6
3
[[24  4  6]
 [ 6  8 10]
 [10 12 14]]


perform matrix addition and matrix multiplication similar matrix addition using matrix identity s1 =[s1]+identity if matrix similar in the multiplication it's take time complexity of n^2 in a nested loop

In [27]:
s = [[1,2,3],[3,4,5],[5,6,7]]
print (s[5:0:-1])

[[5, 6, 7], [3, 4, 5]]


In [28]:
# sum of two matrix:

A = [[1, 2, 3],
     [4, 5, 6]]

B = [[7, 8, 9],
     [1, 2, 3]]

result = []

for i in range(len(A)):
    row = []
    for j in range(len(A[0])):
        row.append(A[i][j] + B[i][j])
    result.append(row)

print(result)

[[8, 10, 12], [5, 7, 9]]
